### ISSUE TITLE
ToDo / Help Needed

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/pip-date#1]
ToDo / Help Needed

- [x] improve the time stamp (TS) heuristic to use more reliable files to search for
- [ ] improve the package type heuristic to show how a package was installed (*wheel* or *sdist*)
- [ ] add an `Environment` column, to show in what virtual environment a package was installed in. 
- [ ] improve highlighting of special package dependencies, such as [these](https://packaging.python.org/key_projects/).  
      (e.g. Current implementation would for 'pip' also highlight any package with "pip" in it.)
- [x] improve the color terminal check in #3 
- [ ] Testing on MacOS
- [x] Add screenshots and text in PyPi (#9)
- [x] Add Python 3.8 compatibility in `setup.py`  
- [x] Merge PR #11 
- [ ] Fix installation paths for windows pythons (#12) if possible

**Comment by AlisterH** [comment]
I believe you could use the crtime package to get creation times on many or perhaps most systems.

**Comment by AlisterH** [comment]
Or maybe I've made a bad assumption, and everything is removed and then replace, nothing is overwritten.
