### ISSUE TITLE
pip-date improvements ToDo list

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/pip-date#19]
Some internal comments suggests some improvements to the `pip-date` script. 
It is probably better to add that info here. 

ToDo:
* [ ] better RegEx for "pip"
* [ ] add flake8 QA ignore comments 
* [ ] fix rounding of floats in [a/c/m]Time
* [ ] Add CLI options:  
* [ ] '-d'          : Enable extra debug info
* [ ] '-e'          : Show `env` column to display `virtualenv` name
* [ ] '-f'          : Force to use opposite (to detected) ctime method for FS
* [ ] '-n'          : Disable colors
* [ ] '-h'          : THIS help/usage message
* [ ] '-v'          : THIS program version
* [ ] '-t <days>'   : To highlight packages installed `<days>` ago
